"use client";
import { useEffect, useState } from "react";
import { AppLogo } from "./app-logo";
import { Icon } from "./icon";
import { connectionStatus, relativeTime, type Connection } from "@/lib/atlas/workspace";
import type { AppCapability } from "@/lib/atlas/apps";

export function ConnectedCluster({ connections, restoring, syncing, onOpen }: { connections: Connection[]; restoring: boolean; syncing: string[]; onOpen: () => void }) {
  return <div className="connected-cluster"><span>{restoring ? "Restoring connections" : "Your connected apps"}</span><div>
    {connections.length ? connections.slice(0, 5).map(c => <button key={c.id} onClick={onOpen} className={`connected-icon ${syncing.includes(c.provider) ? "is-syncing" : ""}`} aria-label={`${c.label}: ${restoring ? "verifying" : connectionStatus(c.status)}`} title={`${c.label} · ${restoring ? "Verifying connection" : connectionStatus(c.status)} · Last sync: ${relativeTime(c.lastSyncAt)}`}><AppLogo provider={c.provider} /><i data-status={restoring ? "connecting" : connectionStatus(c.status)} /></button>) : <button onClick={onOpen} className="connected-icon" title="Connect an app" aria-label="Connect an app"><Icon name="plus" /></button>}
    {connections.length > 5 && <button onClick={onOpen} className="text-button">+{connections.length - 5}</button>}
  </div></div>;
}

export function ConnectedApps({ connections, restoring, syncing, errors, onConnect, onSync, busy }: { connections: Connection[]; restoring: boolean; syncing: string[]; errors: Record<string, string>; onConnect: (provider: string, displayName?: string) => void; onSync: (provider: string) => void; busy?: string | null }) {
  const [apps, setApps] = useState<AppCapability[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [tab, setTab] = useState<"available" | "connected" | "recommended">("available"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/atlas/apps${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ""}`, { cache: "no-store", signal: controller.signal }); const result = await response.json() as { items?: AppCapability[]; error?: string }; if (!response.ok) throw new Error(result.error || "Application registry unavailable."); setApps(result.items ?? []); if (result.error) setError(result.error); } catch (reason) { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Application registry unavailable."); } finally { if (!controller.signal.aborted) setLoading(false); } }, query ? 260 : 0); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query]);
  const categories = ["All", ...new Set(apps.flatMap(item => item.categories))];
  const visible = apps.filter(app => (category === "All" || app.categories.some(item => item === category)) && (tab === "connected" ? app.connected : tab === "recommended" ? !app.connected && ["github", "slack", "notion", "google_drive", "google_calendar"].includes(app.provider) : !app.connected)).slice(0, 30);
  return <div className="apps-page"><p className="eyebrow">Composio application ecosystem</p><h1>Give Atlas the right tools.</h1><p className="page-intro">Browse real Composio toolkits. Atlas only exposes capabilities and connections that the server can verify.</p>
    <div className="app-tabs" role="tablist">{(["connected", "available", "recommended"] as const).map(item => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {tab === "connected" && <div className="integration-list">{connections.map(c => { const status = connectionStatus(c.status); const isSyncing = syncing.includes(c.provider); return <section className="integration-row" key={c.id}><div className="integration-logo"><AppLogo provider={c.provider} size={32} /></div><div className="integration-copy"><h2>{c.label}</h2><p>Authorized connection managed through Atlas and Composio.</p><div className="integration-meta"><span className="connection-label" data-status={status}>{restoring ? "Checking connection…" : isSyncing ? "Syncing…" : status === "connected" ? "Connected" : status === "attention" ? "Needs attention" : "Unavailable"}</span>{c.lastSyncAt && <span>Synced {relativeTime(c.lastSyncAt)}</span>}</div>{errors[c.provider] && <small className="error-text">{errors[c.provider]}</small>}</div>{status === "connected" && ["gmail", "linkedin", "outlook"].includes(c.provider) ? <button className="secondary" disabled={restoring || isSyncing} onClick={() => onSync(c.provider)}><Icon name="refresh" size={16} />{isSyncing ? "Syncing" : "Sync now"}</button> : null}</section>; })}{!connections.length && <div className="empty-state"><Icon name="apps" size={38} /><h2>No connected apps yet.</h2><p>Open Available and choose an application.</p></div>}</div>}
    {tab !== "connected" && <><label className="app-market-search"><Icon name="search" size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search apps, such as GitHub or Notion…" aria-label="Search available apps" /></label><div className="app-categories">{categories.slice(0, 12).map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div>{error && <p className="app-registry-note">{error}</p>}{loading ? <div className="app-card-grid">{[1,2,3,4,5,6].map(item => <i className="app-card-skeleton" key={item} />)}</div> : <div className="app-card-grid">{visible.map(app => <article className="app-card" key={app.toolkitId}><div className="app-card-head"><AppLogo provider={app.provider} size={38} /><div><h2>{app.displayName}</h2><span>{app.categories.join(" · ")}</span></div></div><p>{app.description}</p><div className="capability-pills">{app.searchable && <span>Search</span>}{app.readable && <span>Read</span>}{app.supportsReply && <span>Reply</span>}{app.supportsSend && <span>Send</span>}{app.supportsCreate && <span>Create</span>}{!app.availableTools.length && app.toolsCount > 0 && <span>{app.toolsCount} tools</span>}</div><button className="secondary" disabled={!app.connectable || busy === app.provider} onClick={() => onConnect(app.provider, app.displayName)}>{busy === app.provider ? "Opening…" : app.connectable ? "Connect" : "Setup required"}<Icon name="arrow" size={15} /></button></article>)}{!visible.length && <div className="empty-state"><Icon name="search" size={34} /><h2>No matching applications.</h2><p>Try a toolkit name or another category.</p></div>}</div>}</>}
  </div>;
}
